# Header
menu:
  Home: /
  Archives: /archives
rss:

# Content
excerpt_link: Read More
fancybox: true
canvas_nest: true

# Sidebar
sidebar: right
widgets:
- category
# - tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /css/images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

###########################################
# Github link
github_link: